### ISSUE TITLE
Invalid RBG subset=3 for nof_prb=50 where P=3 error

### ISSUE THREAD

**Issue by arrowtem** [SysSec-KAIST/LTESniffer#24]
Hello , thanks much for LTESniffer 
I am getting this kind of error very often 
Invalid RBG subset=3 for nof_prb=50 where P=3
Is there are any solutions to fix it ? 
![image](https://github.com/SysSec-KAIST/LTESniffer/assets/57949020/ff2f58d7-e55b-4397-a568-aad87b8f2b84)

**Comment by hdtuanss** [comment]
Hi, it seems you had a bad signal quality. It causes the wrong DCI detection and leads to the error you showed. Please place your SDR outdoors to have better signal quality.

**Comment by Rensiyi** [comment]
Could you please provide us with the UHD version you are using. And we also encountered this problem, how did you solve it?Thank you for your help！

**Comment by hdtuanss** [comment]
Hi, I use many UHD versions, as long as it is higher than 4.0, all of them work well with LTESniffer.
About the problem, as I mentioned before, you can place your SDR outdoors. If the error is still happening, you can simply ignore it, because it will not make any problem in the final result (decoded packet in the pcap files).
