### ISSUE TITLE
Decoding procedure

### ISSUE THREAD

**Issue by Novitoll** [SysSec-KAIST/LTESniffer#25]
Per [this DL example](https://github.com/SysSec-KAIST/LTESniffer/blob/main/pcap_file_example/ltesniffer_dl_mode.pcap) in repo,
it seems that the system (i guess Falcon does the same thing) waits until the first RAR message. Until that RAR it keeps decoding MIB, SIB1, SIB2, SIB3.

In that PCAP, RAR occurs (after 1.33 sec) for C-RNTI=70.
So does it mean that the system can not decode DL and UL PDSCH/PUSCH per C-RNTI without knowing dedicated to UE PHY configs (from DL RRCConnectionSetup)? E.g. we have to skip all subframes until we find the beginning of new UE initialization in the network, in other words, we skip all subframes until UL PRACH Preamble -> DL RAR, otherwise we do not know how to decode UE-specific PDSCH regardless what PDCCH DCI Format it is?

Like for TM1, TM2 -- we could've decoded UE's PDSCH and DLSCH TB, as there is no UE feedback required, simple TMs. 

It seems, should be valid for all projects (including Falcon) that decode OTA? Could you please confirm?

**Comment by hdtuanss** [comment]
Hi, LTESniffer does not wait for the first RAR, it starts decoding all subframes as long as it synchronizes with them. 
About UE PHY configs, if LTESniffer does not know the config for a UE yet, it will use a default config to decode. However, the success rate might be low because it uses the wrong config, especially for decoding messages with high modulation schemes (64QAM, 256QAM). One way to solve this problem is to analyze the config in the base station you are listening to in advance, then change the default config of LTESniffer in function ``set_default_of_default_config()`` in MCSTracking.cc.
Note that this solution can improve the success rate when LTESniffer does know config, but in practice, your base station still can assign config differently for UEs, so the success rate can be achieved when LTESniffer can decode RRCConnectionSetup fora RNTI
